export const techCategories = [
  {
    label: "Frontend",
    icon: "🎨",
    color: "from-rose/20 to-roseDark/10",
    borderColor: "border-rose/20",
    glowColor: "#F4A8C0",
    techs: [
      { name: "Vue.js", icon: "💚", level: 85 },
      { name: "Nuxt", icon: "🟢", level: 75 },
      { name: "Tailwind CSS", icon: "💠", level: 90 },
      { name: "PrimeVue", icon: "🌸", level: 70 },
      { name: "TypeScript", icon: "🔷", level: 65 },
    ],
  },
  {
    label: "Backend",
    icon: "⚙️",
    color: "from-lavender/20 to-lavenderDark/10",
    borderColor: "border-lavender/20",
    glowColor: "#C4B5F0",
    techs: [
      { name: "PHP", icon: "🐘", level: 75 },
      { name: "Node.js", icon: "🟩", level: 65 },
      { name: "Prisma ORM", icon: "🔺", level: 70 },
      { name: "REST API", icon: "🔗", level: 80 },
      { name: "JWT", icon: "🔐", level: 75 },
    ],
  },
  {
    label: "Base de données",
    icon: "🗄️",
    color: "from-gold/15 to-terracotta/10",
    borderColor: "border-gold/20",
    glowColor: "#E0C070",
    techs: [
      { name: "MySQL", icon: "🐬", level: 80 },
      { name: "SQLite", icon: "💾", level: 75 },
      { name: "MongoDB", icon: "🍃", level: 55 },
    ],
  },
  {
    label: "Outils & Design",
    icon: "🛠️",
    color: "from-terracotta/15 to-rose/10",
    borderColor: "border-terracotta/20",
    glowColor: "#E09870",
    techs: [
      { name: "Figma", icon: "🎭", level: 80 },
      { name: "Git / GitHub", icon: "🐙", level: 85 },
      { name: "Vite", icon: "⚡", level: 85 },
      { name: "VS Code", icon: "💙", level: 95 },
    ],
  },
];

export const allTechs = [
  { name: "Vue.js" },
  { name: "Nuxt" },
  { name: "Tailwind" },
  { name: "TypeScript" },
  { name: "JavaScript" },
  { name: "PHP" },
  { name: "Node.js" },
  { name: "Prisma" },
  { name: "MySQL" },
  { name: "SQLite" },
  { name: "MongoDB" },
  { name: "Figma" },
  { name: "Git" },
  { name: "Vite" },
  { name: "PrimeVue" },
  { name: "REST API" },
  { name: "JWT" },
  { name: "HTML5" },
  { name: "CSS3" },
  { name: "Linux" },
];
